<?php
/**
 * NomenclatureApi
 * PHP version 7.4
 *
 * @category Class
 * @package  SergeR\MagintB2BPlatformSDK
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Magnit B2B Platform API
 *
 * Описание API для интеграции с Магнит. События от системы Магнит реализуются на стороне Партнера, остальные методы реализованы на стороне Магнит. Сервис Партнера выступает в роли клиента. Общение происходит на основании pull-push-модели, т.е. сервис Партнера как клиент запрашивает информацию о ресурсе, может создавать/обновлять ресурсы, если это необходимо, получать события от системы Магнит. AuthRequest.client_id и AuthRequest.client_secret выдаются по запросу
 *
 * The version of the OpenAPI document: 0.1.33
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.6.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace SergeR\MagintB2BPlatformSDK\Api;

use SergeR\MagintB2BPlatformSDK\MagnitClient;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use SergeR\MagintB2BPlatformSDK\ApiException;
use SergeR\MagintB2BPlatformSDK\Configuration;
use SergeR\MagintB2BPlatformSDK\HeaderSelector;
use SergeR\MagintB2BPlatformSDK\ObjectSerializer;

/**
 * NomenclatureApi Class Doc Comment
 *
 * @category Class
 * @package  SergeR\MagintB2BPlatformSDK
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class NomenclatureApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;/** @var string[] $contentTypes **/
    public const contentTypes = [
        'v1NomenclatureStoresStoreIdPricesGet' => [
            'application/json',
        ],
        'v1NomenclatureStoresStoreIdStocksDeltaGet' => [
            'application/json',
        ],
        'v1NomenclatureStoresStoreIdStocksGet' => [
            'application/json',
        ],
    ];

/**
     * @param MagnitClient $client Magnit API client
     */
    public function __construct(MagnitClient $client)
    {
        $this->client = $client->getHttpClient();
        $this->config = $client->getConfig();
        $this->headerSelector = new HeaderSelector();
    }/**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation v1NomenclatureStoresStoreIdPricesGet
     *
     * Информация по ценам товаров в ТО
     *
     * @param  string $storeId Идентификатор ТО в системе Магнит (required)     *
     * @throws \SergeR\MagintB2BPlatformSDK\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \SergeR\MagintB2BPlatformSDK\Type\StoresPricesItemsV1
     */
    public function v1NomenclatureStoresStoreIdPricesGet($storeId)
    {
        list($response) = $this->v1NomenclatureStoresStoreIdPricesGetWithHttpInfo($storeId);
        return $response;
    }

    /**
     * Operation v1NomenclatureStoresStoreIdPricesGetWithHttpInfo
     *
     * Информация по ценам товаров в ТО
     *
     * @param  string $storeId Идентификатор ТО в системе Магнит (required)     *
     * @throws \SergeR\MagintB2BPlatformSDK\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \SergeR\MagintB2BPlatformSDK\Type\StoresPricesItemsV1, HTTP status code, HTTP response headers (array of strings)
     */
    public function v1NomenclatureStoresStoreIdPricesGetWithHttpInfo($storeId)
    {
        $request = $this->v1NomenclatureStoresStoreIdPricesGetRequest($storeId);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\SergeR\MagintB2BPlatformSDK\Type\StoresPricesItemsV1' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\SergeR\MagintB2BPlatformSDK\Type\StoresPricesItemsV1' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\SergeR\MagintB2BPlatformSDK\Type\StoresPricesItemsV1', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\SergeR\MagintB2BPlatformSDK\Type\StoresPricesItemsV1';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\SergeR\MagintB2BPlatformSDK\Type\StoresPricesItemsV1',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation v1NomenclatureStoresStoreIdPricesGetAsync
     *
     * Информация по ценам товаров в ТО
     *
     * @param  string $storeId Идентификатор ТО в системе Магнит (required)     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v1NomenclatureStoresStoreIdPricesGetAsync($storeId)
    {
        return $this->v1NomenclatureStoresStoreIdPricesGetAsyncWithHttpInfo($storeId)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation v1NomenclatureStoresStoreIdPricesGetAsyncWithHttpInfo
     *
     * Информация по ценам товаров в ТО
     *
     * @param  string $storeId Идентификатор ТО в системе Магнит (required)     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v1NomenclatureStoresStoreIdPricesGetAsyncWithHttpInfo($storeId)
    {
        $returnType = '\SergeR\MagintB2BPlatformSDK\Type\StoresPricesItemsV1';
        $request = $this->v1NomenclatureStoresStoreIdPricesGetRequest($storeId);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'v1NomenclatureStoresStoreIdPricesGet'
     *
     * @param  string $storeId Идентификатор ТО в системе Магнит (required)     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function v1NomenclatureStoresStoreIdPricesGetRequest($storeId)
    {

        // verify the required parameter 'storeId' is set
        if ($storeId === null || (is_array($storeId) && count($storeId) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $storeId when calling v1NomenclatureStoresStoreIdPricesGet'
            );
        }


        $resourcePath = '/v1/nomenclature/stores/{store_id}/prices';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($storeId !== null) {
            $resourcePath = str_replace(
                '{' . 'store_id' . '}',
                ObjectSerializer::toPathValue($storeId),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ], self::contentTypes['v1NomenclatureStoresStoreIdPricesGet'][0],
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer (JWT) authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation v1NomenclatureStoresStoreIdStocksDeltaGet
     *
     * Информация по дельте остатков товара в ТО
     *
     * @param  string $storeId Идентификатор ТО в системе Магнит (required)
     * @param  int $timestampFrom Время с которого нужны изменения по остаткам в формате unix time в секундах (required)     *
     * @throws \SergeR\MagintB2BPlatformSDK\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \SergeR\MagintB2BPlatformSDK\Type\StoresStocksItemsV1|\SergeR\MagintB2BPlatformSDK\Type\BadRequestStoresStockDelta
     */
    public function v1NomenclatureStoresStoreIdStocksDeltaGet($storeId, $timestampFrom)
    {
        list($response) = $this->v1NomenclatureStoresStoreIdStocksDeltaGetWithHttpInfo($storeId, $timestampFrom);
        return $response;
    }

    /**
     * Operation v1NomenclatureStoresStoreIdStocksDeltaGetWithHttpInfo
     *
     * Информация по дельте остатков товара в ТО
     *
     * @param  string $storeId Идентификатор ТО в системе Магнит (required)
     * @param  int $timestampFrom Время с которого нужны изменения по остаткам в формате unix time в секундах (required)     *
     * @throws \SergeR\MagintB2BPlatformSDK\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \SergeR\MagintB2BPlatformSDK\Type\StoresStocksItemsV1|\SergeR\MagintB2BPlatformSDK\Type\BadRequestStoresStockDelta, HTTP status code, HTTP response headers (array of strings)
     */
    public function v1NomenclatureStoresStoreIdStocksDeltaGetWithHttpInfo($storeId, $timestampFrom)
    {
        $request = $this->v1NomenclatureStoresStoreIdStocksDeltaGetRequest($storeId, $timestampFrom);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\SergeR\MagintB2BPlatformSDK\Type\StoresStocksItemsV1' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\SergeR\MagintB2BPlatformSDK\Type\StoresStocksItemsV1' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\SergeR\MagintB2BPlatformSDK\Type\StoresStocksItemsV1', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 400:
                    if ('\SergeR\MagintB2BPlatformSDK\Type\BadRequestStoresStockDelta' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\SergeR\MagintB2BPlatformSDK\Type\BadRequestStoresStockDelta' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\SergeR\MagintB2BPlatformSDK\Type\BadRequestStoresStockDelta', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\SergeR\MagintB2BPlatformSDK\Type\StoresStocksItemsV1';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\SergeR\MagintB2BPlatformSDK\Type\StoresStocksItemsV1',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\SergeR\MagintB2BPlatformSDK\Type\BadRequestStoresStockDelta',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation v1NomenclatureStoresStoreIdStocksDeltaGetAsync
     *
     * Информация по дельте остатков товара в ТО
     *
     * @param  string $storeId Идентификатор ТО в системе Магнит (required)
     * @param  int $timestampFrom Время с которого нужны изменения по остаткам в формате unix time в секундах (required)     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v1NomenclatureStoresStoreIdStocksDeltaGetAsync($storeId, $timestampFrom)
    {
        return $this->v1NomenclatureStoresStoreIdStocksDeltaGetAsyncWithHttpInfo($storeId, $timestampFrom)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation v1NomenclatureStoresStoreIdStocksDeltaGetAsyncWithHttpInfo
     *
     * Информация по дельте остатков товара в ТО
     *
     * @param  string $storeId Идентификатор ТО в системе Магнит (required)
     * @param  int $timestampFrom Время с которого нужны изменения по остаткам в формате unix time в секундах (required)     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v1NomenclatureStoresStoreIdStocksDeltaGetAsyncWithHttpInfo($storeId, $timestampFrom)
    {
        $returnType = '\SergeR\MagintB2BPlatformSDK\Type\StoresStocksItemsV1';
        $request = $this->v1NomenclatureStoresStoreIdStocksDeltaGetRequest($storeId, $timestampFrom);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'v1NomenclatureStoresStoreIdStocksDeltaGet'
     *
     * @param  string $storeId Идентификатор ТО в системе Магнит (required)
     * @param  int $timestampFrom Время с которого нужны изменения по остаткам в формате unix time в секундах (required)     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function v1NomenclatureStoresStoreIdStocksDeltaGetRequest($storeId, $timestampFrom)
    {

        // verify the required parameter 'storeId' is set
        if ($storeId === null || (is_array($storeId) && count($storeId) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $storeId when calling v1NomenclatureStoresStoreIdStocksDeltaGet'
            );
        }

        // verify the required parameter 'timestampFrom' is set
        if ($timestampFrom === null || (is_array($timestampFrom) && count($timestampFrom) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $timestampFrom when calling v1NomenclatureStoresStoreIdStocksDeltaGet'
            );
        }


        $resourcePath = '/v1/nomenclature/stores/{store_id}/stocks_delta';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $timestampFrom,
            'timestamp_from', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            true // required
        ) ?? []);


        // path params
        if ($storeId !== null) {
            $resourcePath = str_replace(
                '{' . 'store_id' . '}',
                ObjectSerializer::toPathValue($storeId),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ], self::contentTypes['v1NomenclatureStoresStoreIdPricesGet'][0],
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer (JWT) authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation v1NomenclatureStoresStoreIdStocksGet
     *
     * Информация по остаткам товаров в ТО
     *
     * @param  string $storeId Идентификатор ТО в системе Магнит (required)     *
     * @throws \SergeR\MagintB2BPlatformSDK\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \SergeR\MagintB2BPlatformSDK\Type\StoresStocksItemsV1
     */
    public function v1NomenclatureStoresStoreIdStocksGet($storeId)
    {
        list($response) = $this->v1NomenclatureStoresStoreIdStocksGetWithHttpInfo($storeId);
        return $response;
    }

    /**
     * Operation v1NomenclatureStoresStoreIdStocksGetWithHttpInfo
     *
     * Информация по остаткам товаров в ТО
     *
     * @param  string $storeId Идентификатор ТО в системе Магнит (required)     *
     * @throws \SergeR\MagintB2BPlatformSDK\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \SergeR\MagintB2BPlatformSDK\Type\StoresStocksItemsV1, HTTP status code, HTTP response headers (array of strings)
     */
    public function v1NomenclatureStoresStoreIdStocksGetWithHttpInfo($storeId)
    {
        $request = $this->v1NomenclatureStoresStoreIdStocksGetRequest($storeId);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\SergeR\MagintB2BPlatformSDK\Type\StoresStocksItemsV1' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\SergeR\MagintB2BPlatformSDK\Type\StoresStocksItemsV1' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\SergeR\MagintB2BPlatformSDK\Type\StoresStocksItemsV1', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\SergeR\MagintB2BPlatformSDK\Type\StoresStocksItemsV1';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\SergeR\MagintB2BPlatformSDK\Type\StoresStocksItemsV1',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation v1NomenclatureStoresStoreIdStocksGetAsync
     *
     * Информация по остаткам товаров в ТО
     *
     * @param  string $storeId Идентификатор ТО в системе Магнит (required)     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v1NomenclatureStoresStoreIdStocksGetAsync($storeId)
    {
        return $this->v1NomenclatureStoresStoreIdStocksGetAsyncWithHttpInfo($storeId)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation v1NomenclatureStoresStoreIdStocksGetAsyncWithHttpInfo
     *
     * Информация по остаткам товаров в ТО
     *
     * @param  string $storeId Идентификатор ТО в системе Магнит (required)     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function v1NomenclatureStoresStoreIdStocksGetAsyncWithHttpInfo($storeId)
    {
        $returnType = '\SergeR\MagintB2BPlatformSDK\Type\StoresStocksItemsV1';
        $request = $this->v1NomenclatureStoresStoreIdStocksGetRequest($storeId);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'v1NomenclatureStoresStoreIdStocksGet'
     *
     * @param  string $storeId Идентификатор ТО в системе Магнит (required)     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function v1NomenclatureStoresStoreIdStocksGetRequest($storeId)
    {

        // verify the required parameter 'storeId' is set
        if ($storeId === null || (is_array($storeId) && count($storeId) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $storeId when calling v1NomenclatureStoresStoreIdStocksGet'
            );
        }


        $resourcePath = '/v1/nomenclature/stores/{store_id}/stocks';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($storeId !== null) {
            $resourcePath = str_replace(
                '{' . 'store_id' . '}',
                ObjectSerializer::toPathValue($storeId),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ], self::contentTypes['v1NomenclatureStoresStoreIdPricesGet'][0],
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer (JWT) authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
