<?php
/**
 * ClaimStatus
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  SergeR\MagintB2BPlatformSDK
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Magnit B2B Platform API
 *
 * Описание API для интеграции с Магнит. События от системы Магнит реализуются на стороне Партнера, остальные методы реализованы на стороне Магнит. Сервис Партнера выступает в роли клиента. Общение происходит на основании pull-push-модели, т.е. сервис Партнера как клиент запрашивает информацию о ресурсе, может создавать/обновлять ресурсы, если это необходимо, получать события от системы Магнит. AuthRequest.client_id и AuthRequest.client_secret выдаются по запросу
 *
 * The version of the OpenAPI document: 0.1.33
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.6.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace SergeR\MagintB2BPlatformSDK\Type;
use \SergeR\MagintB2BPlatformSDK\ObjectSerializer;

/**
 * ClaimStatus Class Doc Comment
 *
 * @category Class
 * @description Статус доставки. Статусы доставки могут добавляться со временем. Нужно учитывать при интеграции. Промежуточные статусы:   created - заказ создан, обработка еще не началась.   estimating - рассчитывается стоимость доставки и проводится валидация.   ready_for_approval - ожидается подтверждение заявки заказчиком.   accepted - валидация завершена.   performer_searching - выполняется поиск курьера.     Если курьер был ранее назначен, но отказался от заказа, то заказ снова попадает в этот статус после performer_found.   performer_found - курьер назначен.   pickup_arrived - курьер прибыл в точку А для получения заказа.   pickuped - заказ получен. курьер движется в точку Б.   delivery_arrived - курьер прибыл в точку Б.   returning - курьер едет обратно в точку А для возврата товара   return_arrived - курьер прибыл в точку А для возврата товара  Терминальные статусы:   delivery_finished - курьер передал заказ клиенту. Доставка выполнена.   delivery_failed - курьер не смог доставить заказ.   cancelled - заказ был отменен со стороны партнера (бесплатная отмена).   cancelled_with_payment - заказ был отменен со стороны партнера (платная отмена).   cancelled_by_service - заказ был отменен со стороны сервиса доставки. Причина отмены в поле cancel_reason.   return_finished - курьер вернул заказ в точку А   return_failed - возврат заказа не удался.
 * @package  SergeR\MagintB2BPlatformSDK
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ClaimStatus
{
    /**
     * Possible values of this enum
     */
    public const CREATED = 'created';

    public const ESTIMATING = 'estimating';

    public const READY_FOR_APPROVAL = 'ready_for_approval';

    public const ACCEPTED = 'accepted';

    public const PERFORMER_SEARCHING = 'performer_searching';

    public const PERFORMER_FOUND = 'performer_found';

    public const PICKUP_ARRIVED = 'pickup_arrived';

    public const PICKUPED = 'pickuped';

    public const DELIVERY_ARRIVED = 'delivery_arrived';

    public const RETURNING = 'returning';

    public const RETURN_ARRIVED = 'return_arrived';

    public const DELIVERY_FINISHED = 'delivery_finished';

    public const DELIVERY_FAILED = 'delivery_failed';

    public const CANCELLED = 'cancelled';

    public const CANCELLED_WITH_PAYMENT = 'cancelled_with_payment';

    public const CANCELLED_BY_SERVICE = 'cancelled_by_service';

    public const RETURN_FINISHED = 'return_finished';

    public const RETURN_FAILED = 'return_failed';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::CREATED,
            self::ESTIMATING,
            self::READY_FOR_APPROVAL,
            self::ACCEPTED,
            self::PERFORMER_SEARCHING,
            self::PERFORMER_FOUND,
            self::PICKUP_ARRIVED,
            self::PICKUPED,
            self::DELIVERY_ARRIVED,
            self::RETURNING,
            self::RETURN_ARRIVED,
            self::DELIVERY_FINISHED,
            self::DELIVERY_FAILED,
            self::CANCELLED,
            self::CANCELLED_WITH_PAYMENT,
            self::CANCELLED_BY_SERVICE,
            self::RETURN_FINISHED,
            self::RETURN_FAILED
        ];
    }
}


