<?php
/**
 * ErrorCodeEnum
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  SergeR\MagintB2BPlatformSDK
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Magnit B2B Platform API
 *
 * Описание API для интеграции с Магнит. События от системы Магнит реализуются на стороне Партнера, остальные методы реализованы на стороне Магнит. Сервис Партнера выступает в роли клиента. Общение происходит на основании pull-push-модели, т.е. сервис Партнера как клиент запрашивает информацию о ресурсе, может создавать/обновлять ресурсы, если это необходимо, получать события от системы Магнит. AuthRequest.client_id и AuthRequest.client_secret выдаются по запросу
 *
 * The version of the OpenAPI document: 0.1.33
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.6.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace SergeR\MagintB2BPlatformSDK\Type;
use \SergeR\MagintB2BPlatformSDK\ObjectSerializer;

/**
 * ErrorCodeEnum Class Doc Comment
 *
 * @category Class
 * @package  SergeR\MagintB2BPlatformSDK
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ErrorCodeEnum
{
    /**
     * Possible values of this enum
     */
    public const SOME_ERROR = 'SOME_ERROR';

    public const FORBIDDEN = 'FORBIDDEN';

    public const ORDER_NOT_FOUND = 'ORDER_NOT_FOUND';

    public const INTERNAL_ERROR = 'INTERNAL_ERROR';

    public const ARTICLE_NOT_FOUND = 'ARTICLE_NOT_FOUND';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::SOME_ERROR,
            self::FORBIDDEN,
            self::ORDER_NOT_FOUND,
            self::INTERNAL_ERROR,
            self::ARTICLE_NOT_FOUND
        ];
    }
}


