<?php
/**
 * MarketplaceParcelStatus
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  SergeR\MagintB2BPlatformSDK
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Magnit B2B Platform API
 *
 * Описание API для интеграции с Магнит. События от системы Магнит реализуются на стороне Партнера, остальные методы реализованы на стороне Магнит. Сервис Партнера выступает в роли клиента. Общение происходит на основании pull-push-модели, т.е. сервис Партнера как клиент запрашивает информацию о ресурсе, может создавать/обновлять ресурсы, если это необходимо, получать события от системы Магнит. AuthRequest.client_id и AuthRequest.client_secret выдаются по запросу
 *
 * The version of the OpenAPI document: 0.1.33
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.6.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace SergeR\MagintB2BPlatformSDK\Type;
use \SergeR\MagintB2BPlatformSDK\ObjectSerializer;

/**
 * MarketplaceParcelStatus Class Doc Comment
 *
 * @category Class
 * @description Статус посылки * &#x60;NEW&#x60;                  - Новая * &#x60;READY_TO_SHIPMENT&#x60;    - Готов к отгрузке * &#x60;AWAITING_DELIVERY&#x60;    - Передается в доставку * &#x60;DELIVERING&#x60;           - В пути * &#x60;RECEIVED&#x60;             - Получен клиентом * &#x60;CANCELED&#x60;             - Отменен
 * @package  SergeR\MagintB2BPlatformSDK
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class MarketplaceParcelStatus
{
    /**
     * Possible values of this enum
     */
    public const _NEW = 'NEW';

    public const READY_TO_SHIPMENT = 'READY_TO_SHIPMENT';

    public const AWAITING_DELIVERY = 'AWAITING_DELIVERY';

    public const DELIVERING = 'DELIVERING';

    public const RECEIVED = 'RECEIVED';

    public const CANCELED = 'CANCELED';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::_NEW,
            self::READY_TO_SHIPMENT,
            self::AWAITING_DELIVERY,
            self::DELIVERING,
            self::RECEIVED,
            self::CANCELED
        ];
    }
}


