<?php
/**
 * OrderCancellationReasonEnum
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  SergeR\MagintB2BPlatformSDK
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Magnit B2B Platform API
 *
 * Описание API для интеграции с Магнит. События от системы Магнит реализуются на стороне Партнера, остальные методы реализованы на стороне Магнит. Сервис Партнера выступает в роли клиента. Общение происходит на основании pull-push-модели, т.е. сервис Партнера как клиент запрашивает информацию о ресурсе, может создавать/обновлять ресурсы, если это необходимо, получать события от системы Магнит. AuthRequest.client_id и AuthRequest.client_secret выдаются по запросу
 *
 * The version of the OpenAPI document: 0.1.33
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.6.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace SergeR\MagintB2BPlatformSDK\Type;
use \SergeR\MagintB2BPlatformSDK\ObjectSerializer;

/**
 * OrderCancellationReasonEnum Class Doc Comment
 *
 * @category Class
 * @description Причина отмены заказа
 * @package  SergeR\MagintB2BPlatformSDK
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class OrderCancellationReasonEnum
{
    /**
     * Possible values of this enum
     */
    public const TEST = 'test';

    public const CUSTOMER_NO_PRODUCT_NEEDED = 'customer_no_product_needed';

    public const CUSTOMER_DELIVERY_TOO_EXPENSIVE = 'customer_delivery_too_expensive';

    public const CUSTOMER_IMPOSSIBLE_ORDER_CHANGE = 'customer_impossible_order_change';

    public const CUSTOMER_NO_REASON = 'customer_no_reason';

    public const ASSEMBLY_IS_LATE = 'assembly_is_late';

    public const ASSEMBLY_NO_REASON = 'assembly_no_reason';

    public const DELIVERY_IS_LATE = 'delivery_is_late';

    public const DELIVERY_NO_COURIER = 'delivery_no_courier';

    public const PAYMENT_NOT_PASSED = 'payment_not_passed';

    public const ORDER_NOT_PICKED_UP = 'order_not_picked_up';

    public const DELIVERY_ORDER_MIXED = 'delivery_order_mixed';

    public const DELIVERY_COURIER_FAULT = 'delivery_courier_fault';

    public const FRAUD = 'fraud';

    public const OTHER = 'other';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::TEST,
            self::CUSTOMER_NO_PRODUCT_NEEDED,
            self::CUSTOMER_DELIVERY_TOO_EXPENSIVE,
            self::CUSTOMER_IMPOSSIBLE_ORDER_CHANGE,
            self::CUSTOMER_NO_REASON,
            self::ASSEMBLY_IS_LATE,
            self::ASSEMBLY_NO_REASON,
            self::DELIVERY_IS_LATE,
            self::DELIVERY_NO_COURIER,
            self::PAYMENT_NOT_PASSED,
            self::ORDER_NOT_PICKED_UP,
            self::DELIVERY_ORDER_MIXED,
            self::DELIVERY_COURIER_FAULT,
            self::FRAUD,
            self::OTHER
        ];
    }
}


