<?php
/**
 * StoreStatusEnum
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  SergeR\MagintB2BPlatformSDK
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Magnit B2B Platform API
 *
 * Описание API для интеграции с Магнит. События от системы Магнит реализуются на стороне Партнера, остальные методы реализованы на стороне Магнит. Сервис Партнера выступает в роли клиента. Общение происходит на основании pull-push-модели, т.е. сервис Партнера как клиент запрашивает информацию о ресурсе, может создавать/обновлять ресурсы, если это необходимо, получать события от системы Магнит. AuthRequest.client_id и AuthRequest.client_secret выдаются по запросу
 *
 * The version of the OpenAPI document: 0.1.33
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.6.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace SergeR\MagintB2BPlatformSDK\Type;
use \SergeR\MagintB2BPlatformSDK\ObjectSerializer;

/**
 * StoreStatusEnum Class Doc Comment
 *
 * @category Class
 * @description Статус магазина
 * @package  SergeR\MagintB2BPlatformSDK
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class StoreStatusEnum implements \JsonSerializable
{
    /**
     * @var string
     * @readonly
     */
    public string $status;

    /**
     * Possible values of this enum
     */
    public const BLOCKED = 'store_blocked';

    public const UNBLOCKED = 'store_unblocked';

    /**
     * @param string $status
     */
    public function __construct(string $status)
    {
        $this->status = $status;
    }

    /**
     * Создать из массива
     *
     * @param array|string $data
     * @return self
     */
    public static function fromArray($data): self
    {
        if (is_array($data)) {
            $data = $data['status'] ?? $data;
        }
        return new self($data);
    }

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::BLOCKED,
            self::UNBLOCKED
        ];
    }

    /**
     * Преобразовать в массив
     *
     * @return array
     */
    public function toArray(): array
    {
        return [
            'status' => $this->status,
        ];
    }

    /**
     * Реализация JsonSerializable
     *
     * @return string
     */
    public function jsonSerialize(): string
    {
        return $this->status;
    }
}
