<?php
/**
 * TaxTypeEnum
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  SergeR\MagintB2BPlatformSDK
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Magnit B2B Platform API
 *
 * Описание API для интеграции с Магнит. События от системы Магнит реализуются на стороне Партнера, остальные методы реализованы на стороне Магнит. Сервис Партнера выступает в роли клиента. Общение происходит на основании pull-push-модели, т.е. сервис Партнера как клиент запрашивает информацию о ресурсе, может создавать/обновлять ресурсы, если это необходимо, получать события от системы Магнит. AuthRequest.client_id и AuthRequest.client_secret выдаются по запросу
 *
 * The version of the OpenAPI document: 0.1.33
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.6.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace SergeR\MagintB2BPlatformSDK\Type;
use \SergeR\MagintB2BPlatformSDK\ObjectSerializer;

/**
 * TaxTypeEnum Class Doc Comment
 *
 * @category Class
 * @description Ставка НДС
 * @package  SergeR\MagintB2BPlatformSDK
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class TaxTypeEnum
{
    /**
     * Possible values of this enum
     */
    public const NO_VAT = 'no_vat';

    public const VAT_0 = 'vat_0';

    public const VAT_10 = 'vat_10';

    public const VAT_20 = 'vat_20';

    public const VAT_10_110 = 'vat_10/110';

    public const VAT_20_120 = 'vat_20/120';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::NO_VAT,
            self::VAT_0,
            self::VAT_10,
            self::VAT_20,
            self::VAT_10_110,
            self::VAT_20_120
        ];
    }
}


